### ISSUE TITLE
electron app - npm run build fails

### ISSUE THREAD

**Issue by eschmidbauer** [lucasavila00/LmScript#2]
Thank you for sharing this project. I am trying to run the electron app but im getting a dependency issue. Is this expected? Thanks in advance. 
![image](https://github.com/lucasavila00/LmScript/assets/7139998/af06c3eb-3e0c-4e5e-9ce5-8b6bf0a09568)

**Comment by lucasavila00** [comment]
Wow, thanks for the early interest.
I haven't finished the first version of the electron app so I haven't written any docs yet.

This error is expected, the electron app uses a pro extension from tiptap.

You'll need to create a **free** Tiptap account and configure npm to download pro extensions, as explained here https://cloud.tiptap.dev/pro-extensions

I hope to remove this pro dependency in the future, possibly using https://github.com/steven-tey/novel/blob/main/packages/headless/src/extensions/drag-and-drop.tsx as inspiration

**Comment by lucasavila00** [comment]
I'll try to set CI to release builds today, too

**Comment by lucasavila00** [comment]
I added a bit of documentation explaining how to run the apps locally.

I also setup GitHub actions to release the electron app and released the latest iteration of the code.


Notice there are a lot of missing features from the app, including very poor error handling in general. I hope to fix these soon.

I'll create issues for the missing features and you can follow the issues being closed to know when the app will be minimally useable.

**Comment by eschmidbauer** [comment]
@lucasavila00 Thank you! Really appreciate you sharing this project
